### ISSUE TITLE
undefined method `authorization=' for #<Google::APIClient::FileStorage:0x007f971ac96978>

### ISSUE THREAD

**Issue by timuckun** [google/google-api-ruby-client#189]
I have the following code which gives the above error

```ruby
def setup()
  client = Google::APIClient.new(:application_name => APPLICATION_NAME,
                                 :application_version => APPLICATION_VERSION)
  file_storage = nil
  begin
    file_storage = Google::APIClient::FileStorage.new(CREDENTIAL_STORE_FILE)
  rescue URI::InvalidURIError
    File.delete CREDENTIAL_STORE_FILE
    file_storage = Google::APIClient::FileStorage.new(CREDENTIAL_STORE_FILE)
  end
  if file_storage.authorization.nil?
    client_secrets = Google::APIClient::ClientSecrets.load
    flow = Google::APIClient::InstalledAppFlow.new(
        :client_id => client_secrets.client_id,
        :client_secret => client_secrets.client_secret,
        :scope => ['https://www.googleapis.com/auth/drive']
    )

    client.authorization = flow.authorize(file_storage)
  else
    client.authorization = file_storage.authorization
  end
  drive = nil
  if File.exists? CACHED_API_FILE
    File.open(CACHED_API_FILE) do |file|
      drive = Marshal.load(file)
    end
  else
    drive = client.discovered_api('drive', API_VERSION)
    File.open(CACHED_API_FILE, 'w') do |file|
      Marshal.dump(drive, file)
    end
  end
  return client, drive
end
```

The error occurs on the line 

```ruby
 client.authorization = flow.authorize(file_storage)
```

The stacktrace is 

```bash
/Users/tim/.gem/ruby/2.1.5/gems/google-api-client-0.8.1.1/lib/google/api_client/auth/file_storage.rb:57:in `write_credentials': undefined method `authorization=' for #<Google::APIClient::FileStorage:0x007f971ac96978> (NoMethodError)
	from /Users/tim/.gem/ruby/2.1.5/gems/google-api-client-0.8.1.1/lib/google/api_client/auth/installed_app.rb:115:in `authorize'
	from ./flow.rb:34:in `setup'
	from ./flow.rb:63:in `<main>'
```

**Comment by RKushnir** [comment]
:+1:

**Comment by doronzRumble** [comment]
same here

**Comment by proapi** [comment]
I had the same problem, downgrade to version 0.7.1 helped
