### ISSUE TITLE
compute_service_account.rb should handle nonexistent 'token' URL.

### ISSUE THREAD

**Issue by mr-salty** [google/google-api-ruby-client#207]
In compute_service_account.rb we do:

        response = connection.get 'http://metadata/computeMetadata/v1beta1/instance/service-accounts/default/token'

However, if the VM was created with --no-scopes this will return an error page instead of the token, which usually leads to a subsequent exception while trying to parse it.

**example exception**

```
error_class="MultiJson::ParseError" error="lexical error: invalid char in json text.\n                                       <!DOCTYPE html> <html lang=en> \n                     (right here) ------^\n" plugin_id="object:3f9bc1d9bd80"
  2015-03-25 22:43:22 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json/adapters/yajl.rb:11:in `parse'
  2015-03-25 22:43:22 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json/adapters/yajl.rb:11:in `load'
  2015-03-25 22:43:22 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json/adapter.rb:21:in `load'
  2015-03-25 22:43:22 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/multi_json-1.11.0/lib/multi_json.rb:119:in `load'
  2015-03-25 22:43:22 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2.rb:81:in `parse_json_credentials'
  2015-03-25 22:43:22 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.7.1/lib/google/api_client/auth/compute_service_account.rb:24:in `fetch_access_token'
  2015-03-25 22:43:22 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/signet-0.5.1/lib/signet/oauth_2/client.rb:956:in `fetch_access_token!'
```

**curl results from the affected machine**

```
$ curl 'http://metadata/computeMetadata/v1beta1/instance/service-accounts/default/token'
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/errors/logo_sm_2.png) no-repeat}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/errors/logo_sm_2_hr.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/errors/logo_sm_2_hr.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:55px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/computeMetadata/v1beta1/instance/service-accounts/default/token</code> was not found on this server.  <ins>That’s all we know.</ins>
```

**Comment by mr-salty** [comment]
Note, I see a similar issue on a --no-scopes machine when using the "fallback" feature for application default credentials (i.e. I configured 'google_app_default' but the env var is unset and there is no credentials file in the well-known location).

2015-04-07 20:27:24 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2015-04-07 20:27:24 +0000 error_class="ArgumentError" error="Invalid content type 'text/html; charset=UTF-8'" plugin_id="object:3f7e67a75b50"
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2.rb:87:in `parse_credentials'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/googleauth-0.4.0/lib/googleauth/compute_engine.rb:81:in `fetch_access_token'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:964:in `fetch_access_token!'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-google-cloud-0.2.2/lib/fluent/plugin/out_google_cloud.rb:263:in `api_client'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-google-cloud-0.2.2/lib/fluent/plugin/out_google_cloud.rb:186:in `block in write'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-google-cloud-0.2.2/lib/fluent/plugin/out_google_cloud.rb:146:in `each'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-google-cloud-0.2.2/lib/fluent/plugin/out_google_cloud.rb:146:in `write'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.61/lib/fluent/buffer.rb:300:in `write_chunk'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.61/lib/fluent/buffer.rb:280:in `pop'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.61/lib/fluent/output.rb:316:in `try_flush'
  2015-04-07 20:27:24 +0000 [warn]: /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.10.61/lib/fluent/output.rb:136:in `run'
