### ISSUE TITLE
Faraday::SSLError in client.execute(:api_method => service.calendar_list.list)

### ISSUE THREAD

**Issue by theinventor** [google/google-api-ruby-client#227]
This code works on heroku, but just stopped working on some dev machines.

Any idea how to resolve?? I tried a few mac osx open-ssl fixes to get new certs installed and it hasn't improved.

![image](https://cloud.githubusercontent.com/assets/610029/7654410/b557905a-fad1-11e4-9069-ab457e0bfe83.png)

Lots of stacktrace:

```
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `connect'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `connect'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:852:in `start'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1369:in `request'
newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
newrelic_rpm (3.10.0.279) lib/new_relic/agent.rb:453:in `disable_all_tracing'
newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
newrelic_rpm (3.10.0.279) lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
newrelic_rpm (3.10.0.279) lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
faraday (0.9.1) lib/faraday/adapter/net_http.rb:82:in `perform_request'
faraday (0.9.1) lib/faraday/adapter/net_http.rb:40:in `block in call'
faraday (0.9.1) lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
faraday (0.9.1) lib/faraday/adapter/net_http.rb:32:in `call'
faraday (0.9.1) lib/faraday/request/url_encoded.rb:15:in `call'
signet (0.5.1) lib/signet/oauth_2/client.rb:933:in `fetch_access_token'
signet (0.5.1) lib/signet/oauth_2/client.rb:956:in `fetch_access_token!'
google-api-client (0.7.1) lib/google/api_client.rb:613:in `block in execute!'
retriable (2.0.2) lib/retriable.rb:53:in `block in retriable'
retriable (2.0.2) lib/retriable.rb:48:in `each'
retriable (2.0.2) lib/retriable.rb:48:in `with_index'
retriable (2.0.2) lib/retriable.rb:48:in `retriable'
google-api-client (0.7.1) lib/google/api_client.rb:595:in `execute!'
google-api-client (0.7.1) lib/google/api_client.rb:634:in `execute'
app/controllers/google_calendars_controller.rb:17:in `block in index'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:35:in `catch'
/Users/troy/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
app/controllers/google_calendars_controller.rb:10:in `index'
actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
```

**Comment by theinventor** [comment]
a team member says some combination of this worked for him;

```
rvm reinstall --disable-binary ruby-2.1.5
rvm osx-ssl-certs update all
and/or
rvm gemset empty
```

we'll close this :)
