### ISSUE TITLE
NoMethodError : join in to_jwt

### ISSUE THREAD

**Issue by bisrael** [google/google-api-ruby-client#228]
example application:

```ruby
require "google/api_client"

client = Google::APIClient.new(:application_name => 'My Script', :application_version => "0.0.1")
# byebug
client.authorization= :google_app_default
client.authorization.fetch_access_token!
```

I get the following error:

```
/Users/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:835:in `to_jwt': undefined method `join' for nil:NilClass (NoMethodError)
	from /Users/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:904:in `generate_access_token_request'
	from /Users/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:935:in `fetch_access_token'
	from /Users/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:964:in `fetch_access_token!'
	from scripts/test.rb:7:in `<top (required)>'
```

tracing through bugsnag I find the error thrown at

```
Catchpoint at /Users/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:835: `undefined method `join' for nil:NilClass' (NoMethodError)

[830, 839] in /Users/user/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb
   830: 
   831:         now = Time.new
   832:         skew = options[:skew] || 60
   833:         assertion = {
   834:           "iss" => self.issuer,
=> 835:           "scope" => self.scope.join(' '),
   836:           "aud" => self.audience,
   837:           "exp" => (now + self.expiry).to_i,
   838:           "iat" => (now - skew).to_i
   839:         }
```

inspecting locals and `self` shows us:

```
(byebug) v l
assertion = nil
now = 2015-05-19 12:03:26 -0700
options = {:connection=>#<Faraday::Connection:0x007fb4bd038ad0 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.1"}, @params={}, @options=#<Farad...
self = #<Google::Auth::ServiceAccountCredentials:0x007fb4b9eb0918>
skew = 60
(byebug) self
#<Google::Auth::ServiceAccountCredentials:0x007fb4b9eb0918 @token_credential_uri=#<Addressable::URI:0x3fda5fc2e59c URI:https://www.googleapis.com/oauth2/v3/token>, @scope=nil, @issuer="redacted@developer.gserviceaccount.com", @expiry=60, @audience="https://www.googleapis.com/oauth2/v3/token", @signing_key=#<OpenSSL::PKey::RSA:0x007fb4bf8572a0>, @extension_parameters={}, @additional_parameters={}, @grant_type=nil, @refresh_token=nil>
```

obviously the `@scope` is `nil`.

I'm not sure who's fault this is, this project or the `googleauth` gem.

Will open an issue there too.

**Comment by sqrrrl** [comment]
Closing since it is better tracked in googleauth.
