### ISSUE TITLE
Issue using latest version with Sinatra

### ISSUE THREAD

**Issue by bogdanRada** [google/google-api-ruby-client#242]
/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require': cannot load such file -- rails/railtie (LoadError)
gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `block in require'
gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
gems/activesupport-4.2.2/lib/active_support/dependencies.rb:274:in `require'
gems/google-api-client-0.8.6/lib/google/api_client/railtie.rb:1:in `<top (required)>'

Would be nice if this line would be only required if Rails is defined
```ruby
require 'rails/railtie'
```
Can this be fixed please?

**Comment by bogdanRada** [comment]
this was happening with activesupport 4.2.2 and i was able to fix it by adding to Gemfile, the gem 'railties' and i had to require before this gem

```ruby
require 'rails/all'
```
and that seems to do the trick.  I can close this issue.
