### ISSUE TITLE
invalid (Google::Apis::ClientError) when patching user with AdminDirectoryV1

### ISSUE THREAD

**Issue by hayesr** [google/google-api-ruby-client#261]
I'm trying to use the Admin API, fetching a user or list of users works, but when I try to patch a user I get an error. Here's my file:

```ruby
require 'googleauth'
require 'google/apis/admin_directory_v1'

ENV['GOOGLE_APPLICATION_CREDENTIALS'] = 'application_default_credentials.json'

scopes = [Google::Apis::AdminDirectoryV1::AUTH_ADMIN_DIRECTORY_USER]

auth = Google::Auth.get_application_default(scopes)
auth.sub = 'adminaccount@example.com'

Google::Apis::RequestOptions.default.authorization = auth

Admin = Google::Apis::AdminDirectoryV1
service = Admin::DirectoryService.new

user = service.get_user('jtmcfakerton23@example.com')
user.update!(primary_email: 'new_email@example.com')
service.patch_user(user.id, user) # => invalid (Google::Apis::ClientError)
```

The stacktrace: 

```
/Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/http_command.rb:194:in `check_status': invalid (Google::Apis::ClientError)
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/api_command.rb:103:in `check_status'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/http_command.rb:162:in `process_response'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/http_command.rb:261:in `execute_once'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:53:in `block in retriable'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `each'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `with_index'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `retriable'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:53:in `block in retriable'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `each'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `with_index'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/retriable-2.0.2/lib/retriable.rb:48:in `retriable'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/lib/google/apis/core/base_service.rb:266:in `execute_or_queue_command'
	from /Users/ehayes/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bundler/gems/google-api-ruby-client-64852feb47f3/generated/google/apis/admin_directory_v1/service.rb:2228:in `patch_user'
	from test.rb:27:in `<main>'
```

I'm using a service account. My credentials are in the json file referenced in my code. I've checked that the account has access to `admin.directory.user` under Security in the Admin panel, and that it's not just read-only access.

Also, I've tried the APIs Explorer here: https://developers.google.com/admin-sdk/directory/v1/reference/users/patch —which worked. 

Then I tried diving in the source to figure out how the request is constructed, it appears to match what I see in the Explorer.

I wasn't sure about how to use the patch_user method, but I think I'm doing it right based on what I could gather from the source. Not sure what I'm doing wrong.

**Comment by hayesr** [comment]
BTW this is with the master branch.

**Comment by hayesr** [comment]
Using 0.9.pre1 (I should have trusted the instructions) I get a different, but more useful error:
```
Google::Apis::ClientError: {"domain"=>"global", "reason"=>"invalid", "message"=>"Invalid value for: Invalid format: \"1970-01-01T00:00:00+00:00\" is malformed at \"+00:00\""}
```
Now I'm trying to figure out the proper way one modifies what seems to be generated code.

**Comment by sqrrrl** [comment]
Was able to reproduce, looks like it's a bug with formatting datetime values. For some reason, the directory API is stricter about the format and is requiring milliseconds even though the docs state otherwise.

Will fix in next release. In the mean time, you don't need to fetch/update the user for this particular use case. Can just as well do:

```
service.patch_user('old_email@example.com', Admin::User.new(primary_email: 'new_email@appsrocks.com'))
```

**Comment by hayesr** [comment]
Got it. :+1: :+1:   Thank you!!

Feel free to close unless you want to leave it open as a reminder.

**Comment by andreydeineko** [comment]
@hayesr sorry for disturbing you so long after you've had the issue - I am facing some troubles with that now. When I am trying to implement it your way, the script breaks on `auth = Google::Auth.get_application_default(scopes)` saying

```ruby
RuntimeError: Unable to read the credential file specified by GOOGLE_APPLICATION_CREDENTIALS: the json is missing the 'type' field
```

When I manually add the `"type": "service_account"` to `"application_default_credentials.json"`, it says

```ruby
RuntimeError: Unable to read the credential file specified by GOOGLE_APPLICATION_CREDENTIALS: missing client_email
```

Then I manyally add `client_email` and the error is

```ruby
RuntimeError: Unable to read the credential file specified by GOOGLE_APPLICATION_CREDENTIALS: missing private_key
```

Question is where do I get the private_key?
