### ISSUE TITLE
Drive Inserts - Parents & appfolder

### ISSUE THREAD

**Issue by travisgalloway** [google/google-api-ruby-client#283]
How are parents, specifically the appfolder for Drive inserts specified in the new API? I'm able to list files from the appfolder, but not upload.

The old API:
```ruby
file = drive.files.insert.request_schema.new({
    'title' => title,
    'description' => description,
    'mimeType' => mime_type,
    'parents' => [{'id' => 'appfolder'}]
})
media = Google::APIClient::UploadIO.new(file_name, mime_type)
```
I've tried a couple variations on the following:
```ruby
drive = Drive::DriveService.new
file = Drive::File.new(title: data[:name], description: data[:description], mime_type: data[:type])
drive.insert_file(file, upload_source: data[:dir], content_type: data[:type]))
```
But, I keep getting the following error:
```bash
Error - #<Google::Apis::ClientError: notFound>

Completed 500 Internal Server Error in 8121ms (ActiveRecord: 0.6ms)

Google::Apis::ClientError - notFound:
  google-api-client (0.9.pre3) lib/google/apis/core/http_command.rb:194:in `check_status'
  google-api-client (0.9.pre3) lib/google/apis/core/api_command.rb:103:in `check_status'
  google-api-client (0.9.pre3) lib/google/apis/core/http_command.rb:162:in `process_response'
  google-api-client (0.9.pre3) lib/google/apis/core/upload.rb:192:in `process_response'
  google-api-client (0.9.pre3) lib/google/apis/core/upload.rb:265:in `execute_once'
  google-api-client (0.9.pre3) lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
```

**Comment by travisgalloway** [comment]
My mistake. I should have read the RubyDoc closer. 
```ruby
drive = Drive::DriveService.new
file = Drive::File.new(title: data[:name], description: data[:description], mime_type: data[:type])
parent = Drive::ParentReference.new(id: 'appfolder', is_root: true)
file.parents = [parent]
drive.insert_file(file, upload_source: data[:dir], content_type: data[:type])
```
