### ISSUE TITLE
could not get past these errors.. I am stuck.. please help..

### ISSUE THREAD

**Issue by raviada** [google/google-api-ruby-client#288]
I am stuck here when uploading multiple files to google cloud storage. Here is what I am trying to do
```
            file_object = Google::Apis::StorageV1::Object.new
            file_object.name = file_name
            file_object.bucket = @bucket.name
            first_token = file_name.partition("/").first
            pp "first_token: #{first_token}"
            if first_token.eql?('images')
              file_object.content_encoding = 'binary'
              file_object.content_type = 'image/jpeg'           
            else
              file_object.content_encoding = 'base64'
              file_object.content_type = 'application/text'           
            end              
            pp file_object
            storage.insert_object(file_object, "websites/#{theme}/#{file_name}") do |result, err|
              if err
                puts "Error message is : #{err.message} and status_code : #{err.status_code}"
              elsif result
                puts "Uploaded: #{result.name}"
              end
            end
```
Here is the stack trace
```
#<Google::Apis::StorageV1::Object:0x007feb6b16b760
 @bucket="sw-durham-family-medicine",
 @content_encoding="base64",
 @content_type="application/text",
 @name="css/animate.css">
Can't convert Google::Apis::StorageV1::Object into String or Array.

/Users/medlio/.rvm/gems/ruby-2.1.2/gems/addressable-2.3.8/lib/addressable/template.rb:700:in `block in transform_capture'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/addressable-2.3.8/lib/addressable/template.rb:686:in `each'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/addressable-2.3.8/lib/addressable/template.rb:686:in `inject'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/addressable-2.3.8/lib/addressable/template.rb:686:in `transform_capture'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/addressable-2.3.8/lib/addressable/template.rb:579:in `block in expand'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/addressable-2.3.8/lib/addressable/template.rb:578:in `gsub!'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/addressable-2.3.8/lib/addressable/template.rb:578:in `expand'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/google-api-client-0.9.pre3/lib/google/apis/core/http_command.rb:138:in `prepare!'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/google-api-client-0.9.pre3/lib/google/apis/core/api_command.rb:57:in `prepare!'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/google-api-client-0.9.pre3/lib/google/apis/core/http_command.rb:93:in `execute'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/google-api-client-0.9.pre3/lib/google/apis/core/base_service.rb:266:in `execute_or_queue_command'
/Users/medlio/.rvm/gems/ruby-2.1.2/gems/google-api-client-0.9.pre3/generated/google/apis/storage_v1/service.rb:1528:in `insert_object'
```

I tried to pass all the required parameters to ```insert_object```, I am getting the following error

```
            storage.insert_object(@bucket.name, file_object, "websites/#{theme}/#{file_name}") do |result, err|
              if err
                puts "Error message is : #{err.message} and status_code : #{err.status_code}"
              elsif result
                puts "Uploaded: #{result.name}"
              end
            end

```
```
#<Google::Apis::StorageV1::Object:0x007fc96ab3af48
 @bucket="sw-durham-family-medicine",
 @content_encoding="base64",
 @content_type="application/text",
 @name="css/animate.css">
wrong number of arguments (3 for 1..2)

/Users/medlio/.rvm/gems/ruby-2.1.2/gems/google-api-client-0.9.pre3/generated/google/apis/storage_v1/service.rb:1503:in `insert_object'

```

What am I doing wrong? Why it is expecting only two input params where I can clearly see that there are 16 params in the method definition.

**Comment by sqrrrl** [comment]
Look at the [method signature](https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/storage_v1/service.rb#L1503).

The first error (can't convert to string) is because you had the first two parameters in the wrong order. First parameter is the bucket name (string), the 2nd the object to insert.

Likewise, the 2nd error is because there are only 2 unnamed parameters supported. The rest are named parameters.
