### ISSUE TITLE
Invalid JWT Signature

### ISSUE THREAD

**Issue by Fabs** [google/google-api-ruby-client#431]
Hey guys,

I am trying to do a server to server authentication on rails, for Google Analytics and outside google services (App Engine and Cloud engine). My code is this one:

```
require 'google/apis/analytics_v3'
require 'json'

Google::Apis.logger.level = Logger::DEBUG
file = File.read('config/google_credentials.json')
opts = JSON.parse(file)

service_account_email = opts['client_email']
key = opts['private_key']

analytics = Google::Apis::AnalyticsV3::AnalyticsService.new

analytics.authorization = Signet::OAuth2::Client.new(
    :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',     
    :audience => 'https://accounts.google.com/o/oauth2/token',
    :scope => 'https://www.googleapis.com/auth/analytics.readonly',
    :issuer => service_account_email,
    :signing_key => key)

analytics.authorization.fetch_access_token!
```

I went to developer console and generated a server_acount json, so my `credentials.json` looks like:

```
{
  "type": "service_account",
  "project_id": "a project",
  "private_key_id": "a very secret private key id",
  "private_key": "a very secure private key",
  "client_email": "mycoolemailredacted@ohsolemio.iam.gserviceaccount.com",
  "client_id": "2183120...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/blablablaredacted"
}
```

I believe its not really a code issue, is something I am doing wrong, so I appreciate any help. Error is:
```
/Users/fabs/.rvm/gems/ruby-2.3.1/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:981:in `fetch_access_token': Authorization failed.  Server message: (Signet::AuthorizationError)
{
  "error" : "invalid_grant",
  "error_description" : "Invalid JWT Signature."
}
	from /Users/fabs/.rvm/gems/ruby-2.3.1/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:998:in `fetch_access_token!'
	from /Users/fabs/.rvm/gems/ruby-2.3.1/gems/googleauth-0.5.1/lib/googleauth/signet.rb:69:in `fetch_access_token!'
	from /Users/fabs/code/escola-digital/lib/google/analytics.rb:35:in `authenticate2'
	from run.rb:3:in `<main>'
```

**Comment by Fabs** [comment]
It looks like that using the information on this PR, I was able to authenticate by doing:
https://github.com/google/google-auth-library-ruby/pull/62/files

```
  Google::Apis.logger.level = Logger::DEBUG

  file = File.read('config/google_credentials.json')

  @analytics = Google::Apis::AnalyticsV3::AnalyticsService.new

  scope = 'https://www.googleapis.com/auth/analytics.readonly'
  authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io: StringIO.new(file), scope: scope)

  authorizer.fetch_access_token!
  @analytics.authorization = authorizer
```

And the code is working for me now.

**Comment by Michael1969** [comment]
thanks, works :o))

**Comment by Ailenswpu** [comment]
Hi
I'm game developer, i want to use my own server to verify my GooglePlay IAP on my rails server,my code is :
```ruby
@client =  Google::Apis::AndroidpublisherV2::AndroidPublisherService.new
 authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
        json_key_io: StringIO.new(File.read "/Users/bigbang003/Desktop/iap_verify.json"),
        scope: "https://www.googleapis.com/auth/androidpublisher")
      authorizer.fetch_access_token!
@client.authorization = authorizer
@client.get_purchase_product("demo package name", "product id", "token")
```
gives me the error:
Error - #<Google::Apis::AuthorizationError: Unauthorized>

@Fabs

**Comment by filipealc** [comment]
I couldn't find anywhere a documentation specifying how I could authenticate through service credentials, thanks @Ailenswpu, your code worked for me, my use case is reading the google sheets through V4 google api.

**Comment by realleoman** [comment]
Hi @Fabs  Thanks for sharing it. It has been useful. After I perform the credential validation, I'm not able to impersonate the user to make a call to his email messages. Any ideas here?
```
class Gsuite::ServiceAccount

  def initialize(person: nil)
    @person = person
  end

  def authorized_client
    @authorized_client = Google::Apis::GmailV1::GmailService.new
    @authorized_client.authorization = Google::Auth::ServiceAccountCredentials.make_creds(
       json_key_io: StringIO.new(File.read AppConfig[:gsuite_service_account][:credentials_file_path]),
      scope: AppConfig[:gsuite_service_account][:scope])
    @authorized_client.authorization.fetch_access_token!
  end
