### ISSUE TITLE
Setting ClientOptions.proxy_url gives "undefined method `host'"

### ISSUE THREAD

**Issue by jamesbursa** [google/google-api-ruby-client#509]
ClientOptions.proxy_url is documented as a string (lib/google/apis/options.rb +37), but setting it results in:

```
undefined method `host' for \"http://gateway1:3128/\":String"
/opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_client_adapter.rb:55:in `configure_client'
```

Passing a URI object does not work either:

```
ArgumentError "unsupported proxy gateway1:3128"
/opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.7.1/lib/httpclient.rb:504:in `proxy='
/opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_client_adapter.rb:55:in `configure_client'
```

This is because httpclient requires a schema in the URL, but only the host and port are used.

The following change fixes this for me. It assumes that proxy_url (which is copied to options.proxy in lib/google/apis/core/base_service.rb +382) is a string, and passes it through unmodified to the httpclient, which has built-in support for extracting the auth already.

```
--- /home/james/http_client_adapter.rb	2016-12-14 19:49:50.626692709 +0000
+++ /opt/google-fluentd/embedded/lib/ruby/gems/2.1.0/gems/google-api-client-0.9.11/lib/google/apis/core/http_client_adapter.rb	2016-12-14 20:07:36.990255831 +0000
@@ -51,11 +51,7 @@
         def configure_client(client, request)
           client.transparent_gzip_decompression = true
           if request.options.proxy
-            proxy = request.options.proxy
-            client.proxy = sprintf('%s:%d', proxy.host, proxy.port)
-            if proxy.user && proxy.password
-              client.set_proxy_auth proxy.user, proxy.password
-            end
+            client.proxy = request.options.proxy
           end
           if request.options.timeout
             client.connect_timeout = request.options.timeout
```

Thanks!

**Comment by sqrrrl** [comment]
Fixed in upcoming 0.11 release.
