### ISSUE TITLE
Error downloading an HTML file with v3 API

### ISSUE THREAD

**Issue by matteofuzz** [google/google-api-ruby-client#639]
I'm trying to download files in a Ruby script. I can list files but can't download them. I try with a very simple text/html one but get an error.

```
{:id=>"1swNBUrj1BIj2RYucSFi4ltX-ZooNVgJI",
 :name=>"test_matteo.html",
 :csv=>nil,
 :folder_name=>"market setup italia - brand",
 :mime_type=>"text/html"}
[2] pry(main)> gdrive.get_file(file[:id], download_dest: "./downloaded.html")
Google::Apis::ClientError: Invalid request
from /Users/xxx/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/google-api-client-0.17.3/lib/google/apis/core/http_command.rb:218:in `check_status'
```

I use SCOPE = Google::Apis::DriveV3::AUTH_DRIVE for the authorization.

I'm using `ruby 2.2.3p173` and the related bundled gems are:

```ruby
...
google-api-client (0.17.3)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (>= 0.5, < 0.7.0)
      httpclient (>= 2.8.1, < 3.0)
      mime-types (~> 3.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
    googleauth (0.6.2)
      faraday (~> 0.12)
      jwt (>= 1.4, < 3.0)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
...
```

**Comment by bantini** [comment]
@matteofuzz Can you share the code that you are using?

**Comment by matteofuzz** [comment]
I'm trying the calls from a pry session

```ruby
[4] pry(main)> file = files.select{|f| f[:name] =~ /matteo/}.first
=> {:id=>"1swNBUrj1BIj2RYucSFi4ltX-ZooNVgJI",
 :name=>"test_matteo.html",
 :csv=>nil,
 :folder_name=>"market setup italia - brand",
 :mime_type=>"text/html"}
[5] pry(main)> gdrive.get_file(file[:id], download_dest: StringIO.new)
Google::Apis::ClientError: Invalid request
from /Users/matteofolin/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/google-api-client-0.17.3/lib/google/apis/core/http_command.rb:218:in `check_status'
```

The file `test_matteo.html` contains only an HTML line

```html
<h1>Test by Matteo</h1>
```

and the code that get the authorization is 

```ruby
require 'google/apis/drive_v3'
require 'googleauth'
require 'googleauth/stores/file_token_store'

require 'fileutils'

OOB_URI = 'xxxxxxxxxxxxxx'
APPLICATION_NAME = 'test-api'
CLIENT_SECRETS_PATH = './config/googleapi_client_secret.json'
CREDENTIALS_PATH = "./config/gdrive-ruby-test-auth-drive.yaml"
SCOPE = Google::Apis::DriveV3::AUTH_DRIVE

##
# Ensure valid credentials, either by restoring from the saved credentials
# files or intitiating an OAuth2 authorization. If authorization is required,
# the user's default browser will be launched to approve the request.
#
# @return [Google::Auth::UserRefreshCredentials] OAuth2 credentials
def authorize
  FileUtils.mkdir_p(File.dirname(CREDENTIALS_PATH))

  client_id = Google::Auth::ClientId.from_file(CLIENT_SECRETS_PATH)
  token_store = Google::Auth::Stores::FileTokenStore.new(file: CREDENTIALS_PATH)
  authorizer = Google::Auth::UserAuthorizer.new(
    client_id, SCOPE, token_store)
  user_id = 'default'
  credentials = authorizer.get_credentials(user_id)
  if credentials.nil?
    url = authorizer.get_authorization_url(base_url: OOB_URI)
    puts "Open the following URL in the browser and enter the resulting code after authorization"
    puts url
    code = STDIN.gets
    credentials = authorizer.get_and_store_credentials_from_code(user_id: user_id, code: code, base_url: OOB_URI)
  end
  credentials
end

# Initialize the API
def init_gdrive_service
  service = Google::Apis::DriveV3::DriveService.new
  service.client_options.application_name = APPLICATION_NAME

  service.authorization = authorize
  service
end
```

**Comment by bantini** [comment]
@matteofuzz How are you initializing gdrive?

**Comment by bantini** [comment]
Closing this issue because there was no response for over a week. Feel free to reopen this issue if the problem persists.
