### ISSUE TITLE
[Firebase Dynamic link] can not create dynamic link by api 

### ISSUE THREAD

**Issue by khacluan** [google/google-api-ruby-client#652]
Hello everyone,
I tried to create firebase dynamic link by REST api, but it doesn't work. It seems could not connect to server.

```ruby
Errno::EHOSTUNREACH: No route to host - No route to host - connect(2) for "firebasedynamiclinks-ipv6.googleapis.com" port 443 (firebasedynamiclinks-ipv6.googleapis.com:443)
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:21:in `create_socket'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient/session.rb:752:in `block in connect'
	from /Users/luand/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
	from /Users/luand/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient.rb:1104:in `follow_redirect'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/httpclient-2.8.3/lib/httpclient.rb:854:in `request'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/google-api-client-0.19.8/lib/google/apis/core/http_command.rb:291:in `execute_once'
... 16 levels...
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/cli/exec.rb:27:in `run'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/cli.rb:362:in `exec'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/bin/bundle:23:in `load'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/bin/bundle:23:in `<main>'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/bin/ruby_executable_hooks:15:in `eval'
	from /Users/luand/.rvm/gems/ruby-2.4.1@ts/bin/ruby_executable_hooks:15:in `<main>'

```

I also tried to connect to server by url 
```bash
curl firebasedynamiclinks-ipv6.googleapis.com

=>

curl: (7) Couldn't connect to server
```

Thanks for any helping!

**Comment by erullmann** [comment]
I had a similar issue, it looks like you can't connect via ipv6 for whatever reason. For me I was in a docker container and need to enable ipv6 support.

**Comment by erullmann** [comment]
Actually I still had some problems after enabling ipv6 support. Apparently firebasedynamiclinks-ipv6.googleapis.com cannot be found in general while firebasedynamiclinks.googleapis.com can. The API uses the former as the base url. I couldn't find the version that changed to the ipv6 url so I ended up doing the dynamic link call myself. Here is some sample ruby code for it:

```
begin
  request_url = "https://firebasedynamiclinks.googleapis.com/v1/shortLinks?key=#{ENV['GOOGLE_API_KEY']}"
  url = URI.parse(request_url)
  req = Net::HTTP::Post.new(url.to_s)
  req.content_type = 'application/json'
  req.body = {'longDynamicLink': "https://#{app_key}.app.goo.gl/?link=#{link}"}.to_json
  res = Net::HTTP.start(url.host,  {use_ssl: true}) {|http|
    http.use_ssl = true
    http.request(req)
  }
  share_link = JSON.parse(res.body)['shortLink']
  logger.warn "setting share link for user #{self.username} to be #{self.share_link}"
rescue Exception => e
   logger.warn "ERROR: #{e}"
end
```

You could also maybe edit a local copy of the gem to change the URL. Hope this helps.

**Comment by khacluan** [comment]
Thanks @erullmann 
I have downgraded to v13.0.2, and it works. :)

**Comment by anuraagbitcot** [comment]
@khacluan gem v 0.13.0.2 works??

**Comment by yurik94** [comment]
Same issue here on dotnet client:

[https://github.com/google/google-api-dotnet-client/issues/1186](https://github.com/google/google-api-dotnet-client/issues/1186)

**Comment by chrisdunelm** [comment]
An internal bug has been filed for this mis-configuration.
The correct hostname should be `firebasedynamiclinks.googleapis.com`.

**Comment by khacluan** [comment]
yeah, to fix this we can override the `FirebaseDynamicLinksService` class

```ruby
require 'google/apis/firebasedynamiclinks_v1'

module Google
  module Apis
    module FirebasedynamiclinksV1
      class FirebaseDynamicLinksService
        def initialize
          super('https://firebasedynamiclinks.googleapis.com/', '')
          @batch_path = 'batch'
        end
      end
    end
  end
end

```

**Comment by chrisdunelm** [comment]
The URL hostname has now been fixed in the [discovery doc](https://www.googleapis.com/discovery/v1/apis/firebasedynamiclinks/v1/rest). So the Ruby client library will now be able to be rebuilt with the correct URL.
