### ISSUE TITLE
cannot load such file -- google/api_client

### ISSUE THREAD

**Issue by slobastev** [google/google-api-ruby-client#701]
I am having an issue with this gem on Mac with High Sierra 10.13.6 and Ubuntu 18.04 Bionic Beaver.

```
irb(main):001:0> require 'google/api_client'
Traceback (most recent call last):
        4: from /home/localadmin/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
        3: from (irb):1
        2: from /home/localadmin/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
        1: from /home/localadmin/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
LoadError (cannot load such file -- google/api_client)
```

google-api-client (0.23.4)

**Comment by dazuma** [comment]
There is no "google/api_client" file. Instead, require the file corresponding to the API you want to use. e.g. to use version v2 of the "drive" API client, do:

```ruby
require "google/apis/drive_v2"
```
